name: flutter_application_4
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  cached_network_image: ^3.2.3
  dio: ^5.4.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get: ^4.6.5
  google_maps_flutter: ^2.1.7
  intl: ^0.17.0
  location: ^4.4.0
  pull_to_refresh: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  # generate: true
  uses-material-design: true
  assets: 
    - assets/image/
  fonts:
    - family: Prompt
      fonts:
        - asset: assets/font/Prompt-Regular.ttf
